In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from bs4 import BeautifulSoup
import re

In [2]:
jame_hazfi = pd.read_csv('workshop_data/Jam-e-hazfi.csv')
jame_hazfi

,Unnamed: 0,Year,Stage,html
0,0,جام حذفی ایران 98-99,یک شانزدهم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,جام حذفی ایران 98-99,یک شانزدهم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,جام حذفی ایران 98-99,یک شانزدهم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,جام حذفی ایران 98-99,یک شانزدهم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,جام حذفی ایران 98-99,یک شانزدهم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
...,...,...,...,...
396,396,جام حذفی ایران 86-87,یک چهارم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
397,397,جام حذفی ایران 86-87,نیمه نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
398,398,جام حذفی ایران 86-87,نیمه نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
399,399,جام حذفی ایران 86-87,فینال,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
400,400,جام حذفی ایران 86-87,فینال,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

In [3]:
teams = pd.read_csv('workshop_data/teams.csv')
teams

,Unnamed: 0,Competition,team,html
0,0,آرشیو جدول های لیگ برتر ایران,گل گهرسیرجان,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,آرشیو جدول های لیگ برتر ایران,نساجی مازندران,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,آرشیو جدول های لیگ برتر ایران,فولاد,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,آرشیو جدول های لیگ برتر ایران,پرسپولیس,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,آرشیو جدول های لیگ برتر ایران,شهر خودرو,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
...,...,...,...,...
246,246,آرشیو جدول های اردیویسه هلند,هیرنفین,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
247,247,آرشیو جدول های اردیویسه هلند,آلکمار,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
248,248,آرشیو جدول های اردیویسه هلند,اوترخت,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
249,249,آرشیو جدول های اردیویسه هلند,نایمخن,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
250,250,جام جهانی 2018 روسیه,دانمارک,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

In [4]:
tables = pd.read_csv('workshop_data/tables.csv')
tables

,Unnamed: 0,Competition,Year,html
0,0,آرشیو جدول های لیگ برتر ایران,لیگ برتر (99-00),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,آرشیو جدول های لیگ برتر ایران,لیگ برتر (98-99),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,آرشیو جدول های لیگ برتر ایران,لیگ برتر (97-98),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,آرشیو جدول های لیگ برتر ایران,لیگ برتر (96-97),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,آرشیو جدول های لیگ برتر ایران,لیگ برتر (95-96),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
...,...,...,...,...
148,148,آرشیو جدول های لیگ برتر بسکتبال ایران,94-95,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
149,149,آرشیو جدول های لیگ برتر بسکتبال ایران,93-94,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
150,150,آرشیو جدول های لیگ برتر بسکتبال ایران,90-91,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
151,151,آرشیو جدول های لیگ برتر بسکتبال ایران,91-92,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
152,152,آرشیو جدول های لیگ برتر بسکتبال ایران,92-93,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

In [5]:
transfers = pd.read_csv('workshop_data/transfers.csv')
transfers.head()

,Unnamed: 0,transfers,html
0,0,نقل و انتقالات لیگ برتر 99-00,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,نقل و انتقالات اروپا 2020-2021,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,نقل و انتقالات نیم فصل لیگ برتر 98-99,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,نقل و انتقالات اروپا 2019-2020,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,نقل و انتقالات لیگ برتر 98-99,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

In [6]:
world_cup = pd.read_csv('workshop_data/WorldCup.csv')
world_cup.head()

,Unnamed: 0,Year,Stage,html
0,0,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

## Jam e Hazfi

### Teams

In [7]:
def get_score(x):
    if '(' not in x:
        return x
    flag = False
    end, start = len(x), 0
    for i in range(len(x)):
        if x[i] == '(' and i != 0: 
            return x[start:i]
        elif x[i] == '(' and i == 0:
            flag = True
        elif flag and x[i] == ')':
            return x[i+1:]
        
        
def get_penalty(x):
    if '(' not in x:
        return 0
    pattern = re.compile(r"\((\d+)\)")
    return pattern.findall(x)[0]
        
def get_data(x, html_tag, team_num=None):
    team = ''
    if team_num == 1:
        team = 'left'
    elif team_num == 2:
        team = 'right'
    if html_tag == 'penalty':
        html_tag = 'team-score '
        return get_penalty(BeautifulSoup(x, 'html.parser').find_all(class_=html_tag + team)[0].get_text())
    elif html_tag == 'team-score ':
        return get_score(BeautifulSoup(x, 'html.parser').find_all(class_=html_tag + team)[0].get_text())
    else:
        return BeautifulSoup(x, 'html.parser').find_all(class_=html_tag + team)[0].get_text()

In [8]:
team_tag = 'team-name '
jame_hazfi['team1'] = jame_hazfi['html'].apply(lambda x: get_data(x, team_tag, 1))
jame_hazfi['team2'] = jame_hazfi['html'].apply(lambda x: get_data(x, team_tag, 2))

### Scores

In [9]:
score_tag = 'team-score '
jame_hazfi['score1'] = jame_hazfi['html'].apply(lambda x: get_data(x, score_tag, 1))
jame_hazfi['score2'] = jame_hazfi['html'].apply(lambda x: get_data(x, score_tag, 2))

### Match Time

In [10]:
time_tag = 'match-time pull-right'
jame_hazfi['time'] = jame_hazfi['html'].apply(lambda x: get_data(x, time_tag))

### Match Date

In [11]:
date_tag = 'match-date pull-right'
jame_hazfi['date'] = jame_hazfi['html'].apply(lambda x: get_data(x, date_tag))

### Penalties

In [12]:
penalty_tag = 'penalty'
jame_hazfi['penalty1'] = jame_hazfi['html'].apply(lambda x: get_data(x, penalty_tag, 1))
jame_hazfi['penalty2'] = jame_hazfi['html'].apply(lambda x: get_data(x, penalty_tag, 2))

In [13]:
tidy_jame_hazfi = jame_hazfi.drop(columns=['Unnamed: 0', 'html'])
tidy_jame_hazfi.to_csv('Tidy Data/tidy_jame_hazfi.csv')

## World Cup

In [14]:
world_cup.head()

,Unnamed: 0,Year,Stage,html
0,0,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,جام جهانی 2014,یک هشتم نهایی,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

### Teams

In [15]:
team_tag = 'team-name '
world_cup['team1'] = world_cup['html'].apply(lambda x: get_data(x, team_tag, 1))
world_cup['team2'] = world_cup['html'].apply(lambda x: get_data(x, team_tag, 2))

### Scores

In [16]:
score_tag = 'team-score '
world_cup['score1'] = world_cup['html'].apply(lambda x: get_data(x, score_tag, 1))
world_cup['score2'] = world_cup['html'].apply(lambda x: get_data(x, score_tag, 2))

### Match Time

In [17]:
time_tag = 'match-time pull-right'
world_cup['time'] = world_cup['html'].apply(lambda x: get_data(x, time_tag))

### Match Date

In [18]:
date_tag = 'match-date pull-right'
world_cup['date'] = world_cup['html'].apply(lambda x: get_data(x, date_tag))

### Penalties

In [19]:
penalty_tag = 'penalty'
world_cup['penalty1'] = world_cup['html'].apply(lambda x: get_data(x, penalty_tag, 1))
world_cup['penalty2'] = world_cup['html'].apply(lambda x: get_data(x, penalty_tag, 2))

In [20]:
tidy_world_cup = world_cup.drop(columns=['Unnamed: 0', 'html'])
tidy_world_cup.to_csv('Tidy Data/tidy_world_cup.csv')

## Tables

In [21]:
tables.head()

,Unnamed: 0,Competition,Year,html
0,0,آرشیو جدول های لیگ برتر ایران,لیگ برتر (99-00),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,آرشیو جدول های لیگ برتر ایران,لیگ برتر (98-99),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,آرشیو جدول های لیگ برتر ایران,لیگ برتر (97-98),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,آرشیو جدول های لیگ برتر ایران,لیگ برتر (96-97),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,آرشیو جدول های لیگ برتر ایران,لیگ برتر (95-96),"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

In [182]:
pd.value_counts(tables['Competition'])

آرشیو جدول های بوندسلیگای آلمان          13
آرشیو جدول های لوشامپیونا فرانسه         13
آرشیو جدول های سری آ ایتالیا             13
آرشیو جدول های لالیگای اسپانیا           13
آرشیو جدول های لیگ دسته یک               13
آرشیو جدول های لیگ برتر انگلیس           13
آرشیو جدول های لیگ برتر والیبال          11
آرشیو جدول های لیگ برتر ایران            10
آرشیو جدول های لیگ برتر بسکتبال ایران     9
آرشیو جدول های لیگ برتر فوتسال            9
لیگ قهرمانان آسیا 2020                    8
جام جهانی 2018 روسیه                      8
لیگ قهرمانان اروپا 2020-2021              8
آرشیو جدول های اردیویسه هلند              6
لیگ جهانی والیبال                         4
 لیگ ملت‌های والیبال                      1
جام جهانی والیبال                         1
Name: Competition, dtype: int64

In [123]:
unique_competitions = tables['Competition'].unique()

In [112]:
volleyball = ['آرشیو جدول های لیگ برتر والیبال',
              'لیگ جهانی والیبال',
              'جام جهانی والیبال', 'لیگ ملت‌های والیبال']
basketball = ['آرشیو جدول های لیگ برتر بسکتبال ایران']
football_footsal = ['آرشیو جدول های لیگ برتر ایران',
                   'آرشیو جدول های لیگ دسته یک',
                   'آرشیو جدول های لیگ برتر انگلیس',
                   'آرشیو جدول های لیگ برتر فوتسال',
                   'آرشیو جدول های اردیویسه هلند',
                   'لیگ قهرمانان اروپا 2020-2021',
                   'جام جهانی 2018 روسیه',
                   'لیگ قهرمانان آسیا 2020',
                   'آرشیو جدول های لالیگای اسپانیا',
                   'آرشیو جدول های سری آ ایتالیا',
                   'آرشیو جدول های لوشامپیونا فرانسه',
                   'آرشیو جدول های بوندسلیگای آلمان']

In [125]:
def get_tables_data(leagues):
    new_df = pd.DataFrame()
    for competition in leagues:
        competitions = tables[tables['Competition'] == competition].reset_index(drop=True)
        for i in range(competitions.shape[0]):
            temp = pd.read_html(competitions['html'][i], header=1)[0] 
            if 'Unnamed: 10' in temp.columns:
                temp = temp.drop(columns=['Unnamed: 10', 'Unnamed: 0'])
            temp['competition'] = competition
            new_df = new_df.append(temp)
    return new_df.reset_index(drop=True)

In [129]:
new_basketball = get_tables_data(basketball)
new_volleyball = get_tables_data(volleyball)
new_football_footsal = get_tables_data(football_footsal)
new_football_footsal

,تيم,بازيها,برد,مساوی,باخت,گل زده,گل خورده,تفاضل گل,امتياز,competition
0,گل گهرسیرجان,2,2,0,0,5,1,4,6,آرشیو جدول های لیگ برتر ایران
1,نساجی مازندران,2,1,1,0,4,1,3,4,آرشیو جدول های لیگ برتر ایران
2,فولاد,2,1,1,0,4,3,1,4,آرشیو جدول های لیگ برتر ایران
3,پرسپولیس,2,1,1,0,1,0,1,4,آرشیو جدول های لیگ برتر ایران
4,شهر خودرو,1,1,0,0,3,0,3,3,آرشیو جدول های لیگ برتر ایران
...,...,...,...,...,...,...,...,...,...,...
1956,بوخوم,34,7,11,16,39,55,-16,32,آرشیو جدول های بوندسلیگای آلمان
1957,مونشن گلادباخ,34,8,7,19,39,62,-23,31,آرشیو جدول های بوندسلیگای آلمان
1958,انرژی کوتبوس,34,8,6,20,30,57,-27,30,آرشیو جدول های بوندسلیگای آلمان
1959,کارلسروهه,34,8,5,21,30,54,-24,29,آرشیو جدول های بوندسلیگای آلمان
1960,آرمنیا بیلفلد,34,4,16,14,29,56,-27,28,آرشیو جدول های بوندسلیگای آلمان

In [127]:
new_basketball.drop(columns=['Unnamed: 1', 'Unnamed: 9'], inplace=True)
new_basketball

,بازی,برد,باخت,گل زده,گل خورده,تفاضل گل,امتیاز,competition
0,26,24,2,1850,1413,437,50,آرشیو جدول های لیگ برتر بسکتبال ایران
1,26,21,5,1929,1514,415,47,آرشیو جدول های لیگ برتر بسکتبال ایران
2,26,20,6,2108,1831,277,46,آرشیو جدول های لیگ برتر بسکتبال ایران
3,26,20,6,1948,1718,230,46,آرشیو جدول های لیگ برتر بسکتبال ایران
4,26,19,7,1943,1697,246,45,آرشیو جدول های لیگ برتر بسکتبال ایران
...,...,...,...,...,...,...,...,...
89,22,9,13,1410,1503,-93,27,آرشیو جدول های لیگ برتر بسکتبال ایران
90,22,8,14,1463,1556,-93,24,آرشیو جدول های لیگ برتر بسکتبال ایران
91,22,6,16,1449,1624,-175,18,آرشیو جدول های لیگ برتر بسکتبال ایران
92,22,6,16,1346,1600,-254,18,آرشیو جدول های لیگ برتر بسکتبال ایران
93,22,3,19,1313,1738,-425,9,آرشیو جدول های لیگ برتر بسکتبال ایران

In [128]:
new_volleyball.drop(columns=['Unnamed: 0'], inplace=True)
new_volleyball

,تيم,امتياز,مسابقات,مسابقات.1,مسابقات.2,جزئيات نتايج,جزئيات نتايج.1,جزئيات نتايج.2,جزئيات نتايج.3,جزئيات نتايج.4,جزئيات نتايج.5,ست,ست.1,ست.2,پوئن,پوئن.1,پوئن.2,competition
0,تيم,امتياز,بازی,برد,باخت,30.0,31.0,32.0,23.0,13.0,3.0,برده,باخته,معدل,برده,باخته,معدل,آرشیو جدول های لیگ برتر والیبال
1,سپاهان,26,10,9,1,4.0,3.0,2.0,1.0,NaN,NaN,29,10,2.900,907,803,1.13,آرشیو جدول های لیگ برتر والیبال
2,فولاد سیرجان,25,9,8,1,5.0,3.0,NaN,1.0,NaN,NaN,26,6,4.333,774,700,1.106,آرشیو جدول های لیگ برتر والیبال
3,شهرداری ارومیه,20,9,7,2,2.0,4.0,1.0,NaN,1.0,1.0,22,12,1.833,798,740,1.078,آرشیو جدول های لیگ برتر والیبال
4,سایپا,19,9,6,3,5.0,1.0,NaN,1.0,2.0,NaN,22,10,2.200,773,710,1.089,آرشیو جدول های لیگ برتر والیبال
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,ایران,12,11,4,7,2.0,1.0,1.0,1.0,2.0,4.0,16,24,0.667,905,893,1.013,جام جهانی والیبال
183,استرالیا,12,11,4,7,2.0,1.0,1.0,1.0,1.0,5.0,15,24,0.625,831,925,0.898,جام جهانی والیبال
184,مصر,8,11,2,9,NaN,1.0,1.0,3.0,1.0,5.0,13,30,0.433,889,976,0.911,جام جهانی والیبال
185,ونزوئلا,3,11,1,10,NaN,NaN,1.0,1.0,3.0,6.0,8,32,0.250,815,981,0.831,جام جهانی والیبال
186,تونس,2,11,0,11,NaN,NaN,NaN,2.0,1.0,8.0,5,33,0.152,747,924,0.808,جام جهانی والیبال

In [122]:
new_basketball.to_csv('Tidy Data/tidy_basketball.csv')
new_volleyball.to_csv('Tidy Data/tidy_volleyball.csv')
new_football_footsal.to_csv('Tidy Data/tidy_football_footsal.csv')

## Teams

In [130]:
teams

,Unnamed: 0,Competition,team,html
0,0,آرشیو جدول های لیگ برتر ایران,گل گهرسیرجان,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
1,1,آرشیو جدول های لیگ برتر ایران,نساجی مازندران,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
2,2,آرشیو جدول های لیگ برتر ایران,فولاد,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
3,3,آرشیو جدول های لیگ برتر ایران,پرسپولیس,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
4,4,آرشیو جدول های لیگ برتر ایران,شهر خودرو,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
...,...,...,...,...
246,246,آرشیو جدول های اردیویسه هلند,هیرنفین,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
247,247,آرشیو جدول های اردیویسه هلند,آلکمار,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
248,248,آرشیو جدول های اردیویسه هلند,اوترخت,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
249,249,آرشیو جدول های اردیویسه هلند,نایمخن,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."
250,250,جام جهانی 2018 روسیه,دانمارک,"<!DOCTYPE HTML PUBLIC ""-//W3C//DTD XHTML 1.0 T..."

In [131]:
def get_team_data(x, data_type):
    data = BeautifulSoup(x, 'html.parser').find('tr', class_='highlight')
    if data is not None:
        if data_type == 'score':
            return int(data.contents[-4].text)
        elif data_type == 'matches':
            return int(data.contents[-2].text)
    else:
        return 0

In [134]:
teams['score'] = teams['html'].apply(lambda x: get_team_data(x, 'score'))
teams['matches'] = teams['html'].apply(lambda x: get_team_data(x, 'matches'))

In [135]:
tidy_teams = teams.drop(columns=['Unnamed: 0', 'html'])
tidy_teams.to_csv('Tidy Data/tidy_teams.csv')
tidy_teams

                       Competition            team  score  matches
0    آرشیو جدول های لیگ برتر ایران    گل گهرسیرجان      2        6
1    آرشیو جدول های لیگ برتر ایران  نساجی مازندران      2        4
2    آرشیو جدول های لیگ برتر ایران           فولاد      2        4
3    آرشیو جدول های لیگ برتر ایران        پرسپولیس      2        4
4    آرشیو جدول های لیگ برتر ایران       شهر خودرو      1        3
..                             ...             ...    ...      ...
246   آرشیو جدول های اردیویسه هلند         هیرنفین      8       16
247   آرشیو جدول های اردیویسه هلند          آلکمار      7       11
248   آرشیو جدول های اردیویسه هلند          اوترخت      8       10
249   آرشیو جدول های اردیویسه هلند          نایمخن     34       34
250           جام جهانی 2018 روسیه         دانمارک      6       10

[251 rows x 4 columns]